// src/lib/api/errorCodes.ts
// 에러 코드 상수, 타입, HTTP 상태 코드 매핑
// 상세 규칙: PROJECT_RULES.md > 4. 에러 코드 체계

export const ERROR_CODES = {
  // ── Common ──
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",

  // ── Validation ──
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_FILTER_VALUE: "INVALID_FILTER_VALUE",
  INVALID_SORT_VALUE: "INVALID_SORT_VALUE",
  INVALID_PAGINATION: "INVALID_PAGINATION",
  INVALID_ID_FORMAT: "INVALID_ID_FORMAT",

  // ── Category ──
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

  // ── Style ──
  STYLE_NOT_FOUND: "STYLE_NOT_FOUND",

  // ── Product ──
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",

  // ── Scraper ──
  SCRAPER_TARGET_UNREACHABLE: "SCRAPER_TARGET_UNREACHABLE",
  SCRAPER_PARSE_FAILED: "SCRAPER_PARSE_FAILED",
  PRICE_DATA_STALE: "PRICE_DATA_STALE",

  // ── Upload ──
  UPLOAD_NO_FILE: "UPLOAD_NO_FILE",
  UPLOAD_INVALID_TYPE: "UPLOAD_INVALID_TYPE",
  UPLOAD_FILE_TOO_LARGE: "UPLOAD_FILE_TOO_LARGE",
  UPLOAD_INVALID_FOLDER: "UPLOAD_INVALID_FOLDER",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  CLOUDINARY_NOT_CONFIGURED: "CLOUDINARY_NOT_CONFIGURED",

  // ── Auth ──
  AUTH_REQUIRED: "AUTH_REQUIRED",
  // AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",   // Phase 4
  // AUTH_FORBIDDEN: "AUTH_FORBIDDEN",           // Phase 4
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  INTERNAL_SERVER_ERROR: 500,
  METHOD_NOT_ALLOWED: 405,
  MISSING_REQUIRED_FIELD: 400,
  INVALID_FILTER_VALUE: 400,
  INVALID_SORT_VALUE: 400,
  INVALID_PAGINATION: 400,
  INVALID_ID_FORMAT: 400,
  CATEGORY_NOT_FOUND: 404,
  STYLE_NOT_FOUND: 404,
  PRODUCT_NOT_FOUND: 404,
  SCRAPER_TARGET_UNREACHABLE: 502,
  SCRAPER_PARSE_FAILED: 502,
  PRICE_DATA_STALE: 200,
  UPLOAD_NO_FILE: 400,
  UPLOAD_INVALID_TYPE: 400,
  UPLOAD_FILE_TOO_LARGE: 413,
  UPLOAD_INVALID_FOLDER: 400,
  UPLOAD_FAILED: 502,
  CLOUDINARY_NOT_CONFIGURED: 503,
  AUTH_REQUIRED: 401,
};
