// prisma/seed-data/celebStyles.ts
// 카테고리당 3~4개, 성별/시즌/색상 골고루 분포

export const SEED_CELEB_STYLES = [
  // ── 아우터 (4개) ──
  {
    id: "seed-style-001",
    celebName: "제니",
    imageUrl: "https://placehold.co/400x500/f0e6d3/333?text=Jennie+Outer",
    categoryId: "seed-cat-outer",
    colors: ["블랙", "화이트"],
    gender: "female",
    season: "spring",
  },
  {
    id: "seed-style-002",
    celebName: "로제",
    imageUrl: "https://placehold.co/400x500/d3e6f0/333?text=Rose+Outer",
    categoryId: "seed-cat-outer",
    colors: ["베이지", "브라운"],
    gender: "female",
    season: "fall",
  },
  {
    id: "seed-style-003",
    celebName: "뷔",
    imageUrl: "https://placehold.co/400x500/d3f0e6/333?text=V+Outer",
    categoryId: "seed-cat-outer",
    colors: ["네이비", "블랙"],
    gender: "male",
    season: "winter",
  },
  {
    id: "seed-style-004",
    celebName: "차은우",
    imageUrl: "https://placehold.co/400x500/e6d3f0/333?text=Eunwoo+Outer",
    categoryId: "seed-cat-outer",
    colors: ["그레이", "화이트"],
    gender: "male",
    season: "spring",
  },

  // ── 상의 (4개) ──
  {
    id: "seed-style-005",
    celebName: "아이유",
    imageUrl: "https://placehold.co/400x500/f0d3e6/333?text=IU+Top",
    categoryId: "seed-cat-top",
    colors: ["화이트", "핑크"],
    gender: "female",
    season: "spring",
  },
  {
    id: "seed-style-006",
    celebName: "지민",
    imageUrl: "https://placehold.co/400x500/e6f0d3/333?text=Jimin+Top",
    categoryId: "seed-cat-top",
    colors: ["블랙", "그레이"],
    gender: "male",
    season: "summer",
  },
  {
    id: "seed-style-007",
    celebName: "카리나",
    imageUrl: "https://placehold.co/400x500/d3d3f0/333?text=Karina+Top",
    categoryId: "seed-cat-top",
    colors: ["블루", "화이트"],
    gender: "female",
    season: "summer",
  },
  {
    id: "seed-style-008",
    celebName: "도영",
    imageUrl: "https://placehold.co/400x500/f0f0d3/333?text=Doyoung+Top",
    categoryId: "seed-cat-top",
    colors: ["베이지", "브라운"],
    gender: "male",
    season: "fall",
  },

  // ── 하의 (3개) ──
  {
    id: "seed-style-009",
    celebName: "수지",
    imageUrl: "https://placehold.co/400x500/f0d3d3/333?text=Suzy+Bottom",
    categoryId: "seed-cat-bottom",
    colors: ["블루", "네이비"],
    gender: "female",
    season: "spring",
  },
  {
    id: "seed-style-010",
    celebName: "정국",
    imageUrl: "https://placehold.co/400x500/d3f0f0/333?text=JK+Bottom",
    categoryId: "seed-cat-bottom",
    colors: ["블랙", "화이트"],
    gender: "male",
    season: "fall",
  },
  {
    id: "seed-style-011",
    celebName: "한소희",
    imageUrl: "https://placehold.co/400x500/e6e6d3/333?text=Sohee+Bottom",
    categoryId: "seed-cat-bottom",
    colors: ["베이지", "화이트"],
    gender: "female",
    season: "summer",
  },

  // ── 원피스/스커트 (3개) ──
  {
    id: "seed-style-012",
    celebName: "윈터",
    imageUrl: "https://placehold.co/400x500/f0e6f0/333?text=Winter+Dress",
    categoryId: "seed-cat-dress",
    colors: ["레드", "화이트"],
    gender: "female",
    season: "summer",
  },
  {
    id: "seed-style-013",
    celebName: "김고은",
    imageUrl: "https://placehold.co/400x500/e6f0e6/333?text=Goeun+Dress",
    categoryId: "seed-cat-dress",
    colors: ["블랙", "그레이"],
    gender: "female",
    season: "fall",
  },
  {
    id: "seed-style-014",
    celebName: "장원영",
    imageUrl: "https://placehold.co/400x500/d3e6e6/333?text=Wonyoung+Dress",
    categoryId: "seed-cat-dress",
    colors: ["핑크", "화이트"],
    gender: "female",
    season: "spring",
  },

  // ── 신발 (3개) ──
  {
    id: "seed-style-015",
    celebName: "블랙핑크 리사",
    imageUrl: "https://placehold.co/400x500/f0d3f0/333?text=Lisa+Shoes",
    categoryId: "seed-cat-shoes",
    colors: ["화이트", "그린"],
    gender: "female",
    season: "summer",
  },
  {
    id: "seed-style-016",
    celebName: "지드래곤",
    imageUrl: "https://placehold.co/400x500/d3d3d3/333?text=GD+Shoes",
    categoryId: "seed-cat-shoes",
    colors: ["블랙", "레드"],
    gender: "male",
    season: "winter",
  },
  {
    id: "seed-style-017",
    celebName: "뉴진스 하니",
    imageUrl: "https://placehold.co/400x500/e6d3e6/333?text=Hanni+Shoes",
    categoryId: "seed-cat-shoes",
    colors: ["베이지", "브라운"],
    gender: "female",
    season: "fall",
  },

  // ── 가방 (3개) ──
  {
    id: "seed-style-018",
    celebName: "블랙핑크 지수",
    imageUrl: "https://placehold.co/400x500/f0f0e6/333?text=Jisoo+Bag",
    categoryId: "seed-cat-bag",
    colors: ["블랙", "브라운"],
    gender: "female",
    season: "fall",
  },
  {
    id: "seed-style-019",
    celebName: "박서준",
    imageUrl: "https://placehold.co/400x500/d3f0d3/333?text=Seojun+Bag",
    categoryId: "seed-cat-bag",
    colors: ["네이비", "블랙"],
    gender: "male",
    season: "winter",
  },
  {
    id: "seed-style-020",
    celebName: "송혜교",
    imageUrl: "https://placehold.co/400x500/e6e6f0/333?text=Hyekyo+Bag",
    categoryId: "seed-cat-bag",
    colors: ["화이트", "베이지"],
    gender: "female",
    season: "spring",
  },
];
