// prisma/seed-data/purchaseLinks.ts
// 상품당 2~3개 플랫폼

export const SEED_PURCHASE_LINKS = [
  // ── prod-001 (ZARA 코트) ──
  {
    id: "seed-link-001",
    productId: "seed-prod-001",
    platformName: "무신사",
    platformLogoUrl: null,
    price: 189000,
    currency: "KRW",
    productUrl: "https://www.musinsa.com/example/001",
    inStock: true,
  },
  {
    id: "seed-link-002",
    productId: "seed-prod-001",
    platformName: "29CM",
    platformLogoUrl: null,
    price: 179000,
    currency: "KRW",
    productUrl: "https://www.29cm.co.kr/example/001",
    inStock: true,
  },
  {
    id: "seed-link-003",
    productId: "seed-prod-001",
    platformName: "W컨셉",
    platformLogoUrl: null,
    price: 195000,
    currency: "KRW",
    productUrl: "https://www.wconcept.co.kr/example/001",
    inStock: false,
  },

  // ── prod-002 (H&M 코트) ──
  {
    id: "seed-link-004",
    productId: "seed-prod-002",
    platformName: "무신사",
    platformLogoUrl: null,
    price: 129000,
    currency: "KRW",
    productUrl: "https://www.musinsa.com/example/002",
    inStock: true,
  },
  {
    id: "seed-link-005",
    productId: "seed-prod-002",
    platformName: "쿠팡",
    platformLogoUrl: null,
    price: 119000,
    currency: "KRW",
    productUrl: "https://www.coupang.com/example/002",
    inStock: true,
  },

  // ── prod-003 (무신사 스탠다드 코트) ──
  {
    id: "seed-link-006",
    productId: "seed-prod-003",
    platformName: "무신사",
    platformLogoUrl: null,
    price: 89000,
    currency: "KRW",
    productUrl: "https://www.musinsa.com/example/003",
    inStock: true,
  },

  // ── prod-004 (COS 코트) ──
  {
    id: "seed-link-007",
    productId: "seed-prod-004",
    platformName: "COS 공식몰",
    platformLogoUrl: null,
    price: 350000,
    currency: "KRW",
    productUrl: "https://www.cos.com/example/004",
    inStock: true,
  },
  {
    id: "seed-link-008",
    productId: "seed-prod-004",
    platformName: "29CM",
    platformLogoUrl: null,
    price: 339000,
    currency: "KRW",
    productUrl: "https://www.29cm.co.kr/example/004",
    inStock: true,
  },

  // ── prod-005 (UNIQLO 티) ──
  {
    id: "seed-link-009",
    productId: "seed-prod-005",
    platformName: "유니클로 공식몰",
    platformLogoUrl: null,
    price: 19900,
    currency: "KRW",
    productUrl: "https://www.uniqlo.com/kr/example/005",
    inStock: true,
  },
  {
    id: "seed-link-010",
    productId: "seed-prod-005",
    platformName: "쿠팡",
    platformLogoUrl: null,
    price: 21900,
    currency: "KRW",
    productUrl: "https://www.coupang.com/example/005",
    inStock: true,
  },

  // ── prod-006 (8SECONDS 블라우스) ──
  {
    id: "seed-link-011",
    productId: "seed-prod-006",
    platformName: "무신사",
    platformLogoUrl: null,
    price: 39900,
    currency: "KRW",
    productUrl: "https://www.musinsa.com/example/006",
    inStock: true,
  },
  {
    id: "seed-link-012",
    productId: "seed-prod-006",
    platformName: "29CM",
    platformLogoUrl: null,
    price: 35900,
    currency: "KRW",
    productUrl: "https://www.29cm.co.kr/example/006",
    inStock: true,
  },

  // ── prod-008 (리바이스 진) ──
  {
    id: "seed-link-013",
    productId: "seed-prod-008",
    platformName: "무신사",
    platformLogoUrl: null,
    price: 109000,
    currency: "KRW",
    productUrl: "https://www.musinsa.com/example/008",
    inStock: true,
  },
  {
    id: "seed-link-014",
    productId: "seed-prod-008",
    platformName: "리바이스 공식몰",
    platformLogoUrl: null,
    price: 119000,
    currency: "KRW",
    productUrl: "https://www.levi.co.kr/example/008",
    inStock: true,
  },
  {
    id: "seed-link-015",
    productId: "seed-prod-008",
    platformName: "쿠팡",
    platformLogoUrl: null,
    price: 99000,
    currency: "KRW",
    productUrl: "https://www.coupang.com/example/008",
    inStock: false,
  },

  // ── prod-010 (ZARA 원피스) ──
  {
    id: "seed-link-016",
    productId: "seed-prod-010",
    platformName: "무신사",
    platformLogoUrl: null,
    price: 79900,
    currency: "KRW",
    productUrl: "https://www.musinsa.com/example/010",
    inStock: true,
  },
  {
    id: "seed-link-017",
    productId: "seed-prod-010",
    platformName: "W컨셉",
    platformLogoUrl: null,
    price: 74900,
    currency: "KRW",
    productUrl: "https://www.wconcept.co.kr/example/010",
    inStock: true,
  },

  // ── prod-012 (마르니 가방) ──
  {
    id: "seed-link-018",
    productId: "seed-prod-012",
    platformName: "29CM",
    platformLogoUrl: null,
    price: 890000,
    currency: "KRW",
    productUrl: "https://www.29cm.co.kr/example/012",
    inStock: true,
  },
  {
    id: "seed-link-019",
    productId: "seed-prod-012",
    platformName: "W컨셉",
    platformLogoUrl: null,
    price: 870000,
    currency: "KRW",
    productUrl: "https://www.wconcept.co.kr/example/012",
    inStock: true,
  },

  // ── prod-013 (마뗑킴 에코백) ──
  {
    id: "seed-link-020",
    productId: "seed-prod-013",
    platformName: "무신사",
    platformLogoUrl: null,
    price: 68000,
    currency: "KRW",
    productUrl: "https://www.musinsa.com/example/013",
    inStock: true,
  },
  {
    id: "seed-link-021",
    productId: "seed-prod-013",
    platformName: "쿠팡",
    platformLogoUrl: null,
    price: 62000,
    currency: "KRW",
    productUrl: "https://www.coupang.com/example/013",
    inStock: true,
  },
];
